# Generated by Django 5.2.8 on 2025-12-04 02:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_name_meal_food_name_remove_meal_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sleep",
            options={},
        ),
        migrations.AlterModelOptions(
            name="weighin",
            options={},
        ),
        migrations.RemoveField(
            model_name="sleep",
            name="date",
        ),
        migrations.RemoveField(
            model_name="sleep",
            name="sleep_quality",
        ),
        migrations.RemoveField(
            model_name="weighin",
            name="date",
        ),
        migrations.RemoveField(
            model_name="weighin",
            name="note",
        ),
        migrations.RemoveField(
            model_name="weighin",
            name="weight_lbs",
        ),
        migrations.AddField(
            model_name="sleep",
            name="logged_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="weighin",
            name="logged_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="weighin",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=70.0,
                help_text="Body weight in kg (30–400).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(400),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout",
            name="calories",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Estimated calories burned (0–5000).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="calories",
            field=models.PositiveIntegerField(
                help_text="Calories in kcal (0–5000).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="food_name",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="HTML tags are not allowed in this field.",
                        regex="^[^<>]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="protein",
            field=models.PositiveIntegerField(
                help_text="Protein in grams (0–300).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sleep",
            name="hours",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Hours slept (0–24).",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sleep",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sleeps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="weighin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weighins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="duration",
            field=models.PositiveIntegerField(
                help_text="Duration in minutes (1–600).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(600),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes about this workout (no HTML).",
                validators=[
                    django.core.validators.RegexValidator(
                        message="HTML tags are not allowed in this field.",
                        regex="^[^<>]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="workout_type",
            field=models.CharField(
                choices=[
                    ("run", "Run"),
                    ("strength", "Strength"),
                    ("treadmill", "Treadmill"),
                    ("other", "Other"),
                ],
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="HTML tags are not allowed in this field.",
                        regex="^[^<>]*$",
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="ProgressPhoto",
        ),
    ]
